# vim:ft=yaml
execute_after:
  - feh --bg-fill ~/Pictures/bg/gopher.jpg

on_failure:
  - xrandr --auto

rules:
  - name: Docking Station
    outputs_connected: 
      - DP-0-SAM-3893-1113217602-U32J59x-H4ZN200053
      - DP1-AOC-9591-339-Q2577W-ADQF59A000339
    configure_row:
      - DP1
      - DP-0
    atomic: true
    primary: DP-0

  - name: Mobile
    outputs_connected:
      - eDP1
      - DP1-DZX-5504-0-Z1-000000000000
    configure_row:
      - DP1
      - eDP1
    atomic: true
    primary: eDP1

  - name: Mobile nvidia
    outputs_connected:
      - eDP1
      - DP-0-DZX-5504-0-Z1-000000000000
    configure_row:
      - DP-0
      - eDP1
    atomic: true
    primary: eDP1

  - name: Misc HDMI
    outputs_connected:
      - eDP1
      - HDMI1
    configure_row:
      - eDP1
      - HDMI1
    atomic: true
    primary: eDP1

  - name: Fallback
    configure_single: eDP1
    primary: eDP1
