#!/bin/sh
echo $(
    dbus-send --print-reply \
        --session \
        --dest=org.mpris.MediaPlayer2.spotify \
        /org/mpris/MediaPlayer2 \
        org.freedesktop.DBus.Properties.Get \
        string:'org.mpris.MediaPlayer2.Player' \
        string:'Metadata' \
    | awk '
        BEGIN {
            RS=" entry\\(";
            FS="\""
        };
        /artist/ {
            artist = $4
        };
        /title/ {
            title = $4
        }
        END {
            if (title) {
                print title " - " artist
            } else {
                print "Not Playing"
            }
        }
    '
)
