#!/bin/sh
echo $(
    dbus-send --print-reply \
        --session \
        --dest=org.mpris.MediaPlayer2.spotify \
        /org/mpris/MediaPlayer2 \
        org.freedesktop.DBus.Properties.Get \
        string:'org.mpris.MediaPlayer2.Player' \
        string:'Metadata' \
    | $(dirname $0)/spotify-parse \
    | sed 's/&/+/ig'
)
