#!/bin/bash
f=$(ls ~/Documents/Github/ | awk -v RS=" " '{print}' | dmenu -l 10 -p "Open Project" | tr -d '\n')
if [[ ! -z "$f" ]]; then
	"/home/indeedhat/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/183.5429.30/bin/idea.sh" ~/Documents/Github/$f 
fi
